import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import Footer from "./components/Footer";

import "./globals.css";

const inter = League_Spartan({ subsets: ["latin"], weight: ["100", "500"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
